#include "Motor.h"
#include "GPIO.h"
#include "Port.h"
#include "Type.h"


void Motor_Init(void)
{

	//GPIO_SetPinDirection(MOTOR_1_PORT,MOTOR_1_ENABLE,GPIO_DIRECTION_OUTPUT);
    GPIO_SetPinDirection(MOTOR_1_PORT,MOTOR_1_IN1,GPIO_DIRECTION_OUTPUT);
	GPIO_SetPinDirection(MOTOR_1_PORT,MOTOR_1_IN2,GPIO_DIRECTION_OUTPUT);
	
	//GPIO_SetPinState(MOTOR_1_PORT,MOTOR_1_ENABLE,GPIO_STATE_LOW);
	GPIO_SetPinState(MOTOR_1_PORT,MOTOR_1_IN1,GPIO_STATE_LOW);
	GPIO_SetPinState(MOTOR_1_PORT,MOTOR_1_IN2,GPIO_STATE_LOW);
	
	/************Motor_2********/
	//GPIO_SetPinDirection(MOTOR_2_PORT,MOTOR_2_ENABLE,GPIO_DIRECTION_OUTPUT);
    GPIO_SetPinDirection(MOTOR_2_PORT,MOTOR_2_IN1,GPIO_DIRECTION_OUTPUT);
	GPIO_SetPinDirection(MOTOR_2_PORT,MOTOR_2_IN2,GPIO_DIRECTION_OUTPUT);
	
	//GPIO_SetPinState(MOTOR_2_PORT,MOTOR_2_ENABLE,GPIO_STATE_LOW);
	GPIO_SetPinState(MOTOR_2_PORT,MOTOR_2_IN1,GPIO_STATE_LOW);
	GPIO_SetPinState(MOTOR_2_PORT,MOTOR_2_IN2,GPIO_STATE_LOW);

	/************Motor_3********/
	//GPIO_SetPinDirection(MOTOR_3_PORT,MOTOR_3_ENABLE,GPIO_DIRECTION_OUTPUT);
    GPIO_SetPinDirection(MOTOR_3_PORT,MOTOR_3_IN1,GPIO_DIRECTION_OUTPUT);
	GPIO_SetPinDirection(MOTOR_3_PORT,MOTOR_3_IN2,GPIO_DIRECTION_OUTPUT);
	
	//GPIO_SetPinState(MOTOR_3_PORT,MOTOR_3_ENABLE,GPIO_STATE_LOW);
	GPIO_SetPinState(MOTOR_3_PORT,MOTOR_3_IN1,GPIO_STATE_LOW);
	GPIO_SetPinState(MOTOR_3_PORT,MOTOR_3_IN2,GPIO_STATE_LOW);

	/************Motor_4********/
	//GPIO_SetPinDirection(MOTOR_4_PORT,MOTOR_4_ENABLE,GPIO_DIRECTION_OUTPUT);
    GPIO_SetPinDirection(MOTOR_4_PORT,MOTOR_4_IN1,GPIO_DIRECTION_OUTPUT);
	GPIO_SetPinDirection(MOTOR_4_PORT,MOTOR_4_IN2,GPIO_DIRECTION_OUTPUT);
	
	//GPIO_SetPinState(MOTOR_4_PORT,MOTOR_4_ENABLE,GPIO_STATE_LOW);
	GPIO_SetPinState(MOTOR_4_PORT,MOTOR_4_IN1,GPIO_STATE_LOW);
	GPIO_SetPinState(MOTOR_4_PORT,MOTOR_4_IN2,GPIO_STATE_LOW);


}

void Motor_Update(void)
{


}

void Motor_Start(void)
{

}

void Motor_Stop(void)
{

}

void Motor_GoForward(void)
{
    /************Motor_1********/
	//GPIO_SetPinState(MOTOR_1_PORT,MOTOR_1_ENABLE,GPIO_STATE_HIGH);
	GPIO_SetPinState(MOTOR_1_PORT,MOTOR_1_IN1,GPIO_STATE_HIGH);
	GPIO_SetPinState(MOTOR_1_PORT,MOTOR_1_IN2,GPIO_STATE_LOW);
	
	/************Motor_2********/
	//GPIO_SetPinState(MOTOR_2_PORT,MOTOR_2_ENABLE,GPIO_STATE_HIGH);
	GPIO_SetPinState(MOTOR_2_PORT,MOTOR_2_IN1,GPIO_STATE_HIGH);
	GPIO_SetPinState(MOTOR_2_PORT,MOTOR_2_IN2,GPIO_STATE_LOW);
	
	/************Motor_3********/
	//GPIO_SetPinState(MOTOR_3_PORT,MOTOR_3_ENABLE,GPIO_STATE_HIGH);
	GPIO_SetPinState(MOTOR_3_PORT,MOTOR_3_IN1,GPIO_STATE_HIGH);
	GPIO_SetPinState(MOTOR_3_PORT,MOTOR_3_IN2,GPIO_STATE_LOW);
	
	/************Motor_4********/
	//GPIO_SetPinState(MOTOR_4_PORT,MOTOR_4_ENABLE,GPIO_STATE_HIGH);
	GPIO_SetPinState(MOTOR_4_PORT,MOTOR_4_IN1,GPIO_STATE_HIGH);
	GPIO_SetPinState(MOTOR_4_PORT,MOTOR_4_IN2,GPIO_STATE_LOW);
}

void Motor_SetSpeed(Motor_Speed_t speed)
{
    
}